
POST http://localhost:8080/login
Content-Type: application/json

{
  "email":"adis2@gmail.de",
  "password": "123456"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstname":"Adis",
  "email": "adis5@gmail.de",
  "password": "123456"
}

###
DELETE http://localhost:8080/items/item/0b5dae28-e5ac-41b2-b77a-3d37f9114187
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NTE2OTA5OSwiZXhwIjoxNTg1MTY5Njk5fQ.O3quvZ3UwYB71rDVRRrbxYkgzdjoYuvXzQOt8Gafe64

###
POST http://localhost:8080/items/item/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NjcyODUzMiwiZXhwIjoxNTg3NTkyNTMyfQ.ZoF2Z-qkfYUeuQkcLA3lbRD005TDTaOUbXYjbHieF14
Content-Type: application/json

{
  "title":"Golf 4",
  "price": 4000,
  "description": "Golf 4 Bj 2004"
}
###
###
PUT http://localhost:8080/items/item/6545433b-4131-407c-93da-9c93b4dc3b42
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NTE2ODQ1NywiZXhwIjoxNTg1MTY5MDU3fQ.4qZY6055AJ0UVSy_WsJ3E6M2kpcMgQt8wtGhTj2-TPk
Content-Type: application/json

{
  "title":"ASD",
  "numLikes": 12,
  "price": 1234
}
###

GET http://localhost:8080/favorite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NTI1MjE2NSwiZXhwIjoxNTg1MjUyNzY1fQ.S4iL75dJIUn7jLczbRmm7iDdAVbBhyEJOsP1YNXB5ik
###
POST http://localhost:8080/favorite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NTI1MjE2NSwiZXhwIjoxNTg1MjUyNzY1fQ.S4iL75dJIUn7jLczbRmm7iDdAVbBhyEJOsP1YNXB5ik
Content-Type: application/json

{
  "id": "15e33e3a-0668-4ebd-9cff-3848ef61e70c"
}

###
DELETE http://localhost:8080/favorite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NTI1MjE2NSwiZXhwIjoxNTg1MjUyNzY1fQ.S4iL75dJIUn7jLczbRmm7iDdAVbBhyEJOsP1YNXB5ik
Content-Type: application/json

{
  "id": "15e33e3a-0668-4ebd-9cff-3848ef61se70c"
}