GET http://localhost:8080/login/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkaXMiLCJpYXQiOjE1ODQ4OTU3MTMsImV4cCI6MTU4NDg5NTcxOH0.oE715V00gIDNYrT521Co47Z365y1RLgzmBpF2w0b1OU
###

DELETE http://localhost:8080/login/delete
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkaXMiLCJpYXQiOjE1ODQ4OTY0MjV9.T368ATj3ZlAGbICN4Pt7QXes_ldE4ANXKJXlMY7RQ3E"
}

###
POST http://localhost:8080/login/token
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkaXMiLCJpYXQiOjE1ODQ4OTY0MjV9.T368ATj3ZlAGbICN4Pt7QXes_ldE4ANXKJXlMY7RQ3E"
}

###
POST http://localhost:8080/login/
Content-Type: application/json

{
  "username":"Adis"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstname":"Adis",
  "email": "12345@asda.de",
  "password": "123456"
}