
POST http://localhost:8080/login
Content-Type: application/json

{
  "email":"adis2@gmail.de",
  "password": "123456"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstname":"Adis",
  "email": "adis2@gmail.de",
  "password": "123456"
}

###
DELETE http://localhost:8080/items/item/7b7b158f-699b-40ca-8482-9ad271449bd5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NTE2Njc3OSwiZXhwIjoxNTg1MTY3Mzc5fQ.92vQARlYttEJ_k6BGY8KehS2gveIaJ5PSp5b-rvShGc

###
POST http://localhost:8080/items/item/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NTE2ODQ1NywiZXhwIjoxNTg1MTY5MDU3fQ.4qZY6055AJ0UVSy_WsJ3E6M2kpcMgQt8wtGhTj2-TPk
Content-Type: application/json

{
  "title":"Buch",
  "price": 10
}
###

PUT http://localhost:8080/items/item/ce77db12-4a3a-4c8d-bb5e-3d5415e83ecb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNTg0MDBjNmUtNDAzOS00YzVjLTkyMGMtN2IzMWNhZjU4MTZkIiwiZW1haWwiOiJhZGlzMkBnbWFpbC5kZSIsImlhdCI6MTU4NTE2NTkyOCwiZXhwIjoxNTg1MTY2NTI4fQ.97Z27zGeDvh2CQ3pH-Q3uQQ26D82KIUYWfVllTbmHcc
Content-Type: application/json

{
  "title":"Buch",
  "numLikes": 12
}